Add minimum supported rustc version.
ebfull/pcap pull request #131
Opened 2020-09-04 07:39 UTC by sekineh

Closes #130

2020-09-04 09:54 UTC, Wojtek242 requested changes
Those jobs failed due to clippy warnings though (as I set clippy warnings to fail CI). The solution is to fix the warnings or to allow them. I think if it's easy enough to fix the warnings we should go for that as 1.44 is quite a recent version. If it's too much hassle, I'd change CI to not fail on clippy warnings and go with an older version of the compiler. 

Note, it's probably easier to do the bisection search if you disable clippy first and only fix the warnings once you find the actual oldest version of the compiler that still works.

2020-09-04 11:25 UTC, sekineh commented
> Those jobs failed due to clippy warnings though (as I set clippy warnings to fail CI). The solution is to fix the warnings or to allow them. I think if it's easy enough to fix the warnings we should go for that as 1.44 is quite a recent version. If it's too much hassle, I'd change CI to not fail on clippy warnings and go with an older version of the compiler.
> 

Hmm, do you suppose 1.44.1 is too new?

I don't think changing CI to not fail on clippy warning is a good idea in order to keep code healthy. In that case, we need to review clippy output manually. Because we have a lot of jobs, we won't have enough passion to see output by clicking details.

> Note, it's probably easier to do the bisection search if you disable clippy first and only fix the warnings once you find the actual oldest version of the compiler that still works.

Many projects run clippy on stable only.  Given clippy default changes over time and it's less important than build failures, I'd suggest to run clippy on stable only.
I think it's a reasonable trade off to get an earlier MSRV.

2020-09-04 11:41 UTC, Wojtek242 commented
> Many projects run clippy on stable only. Given clippy default changes over time and it's less important than build failures, I'd suggest to run clippy on stable only.

Sounds reasonable to me since they pass on stable.

2020-09-04 11:42 UTC, Wojtek242 commented
In that case just removing clippy from builds other than stable would mean we can support an older version of rustc.

2020-09-05 06:29 UTC, sekineh commented
My memo:
Dependency `bytes` 1.5.6 fails on 1.37.1. They don't have explicit MSRV claim.
https://github.com/ebfull/pcap/pull/131/checks?check_run_id=1074911356

2020-09-05 07:05 UTC, sekineh commented
I didn't know how to resolve review requests, I'm requesting new review from @Wojtek242 .

2020-09-05 07:16 UTC, merged